# The URL the site will be built for
base_url = "https://hackers267.github.com/lunarvim-note"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

theme = "blow"

default_language = "zh"

taxonomies = [
  {name = "tags", rss = true},
]
[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Put all your custom variables here
enable_multilingue = false
enable_search = false
enable_sidebar = false
enable_navber = true
enable_adsense = false

[extra.navbar]
items = [
 { lang = "zh", links = [
   { url = "/", name = "主页" },
   { url = "/post", name = "文章" },
   { url = "/tags", name = "标签"},
   { url = "/about", name = "关于" },
  ]},
]
title = "LunarVim"

[extra.sidebar]
items = [
  { lang = "zh", links = [
    { url = "/about", name = "关于" },
    { url = "/post", name = "文章" },
  ]},
]

[extra.index]
title = "silence_zhpf's LunarVim"
image = "https://www.lunarvim.org/img/lunarvim_icon.png"
image_alt = "LunarVim"

[extra.social]
github = "https://github.com/hackers267/lunarvim-note"
gitlab = false
twitter = false
linkedin = false
stackoverflow = false
telegram = false
email = "silence_zhpf@aliyun.com"

[extra.favicon]
favicon = "https://www.lunarvim.org/img/lunarvim_icon.png"
favicon_16x16 = "https://www.lunarvim.org/img/lunarvim_icon.png"
favicon_32x32 = "https://www.lunarvim.org/img/lunarvim_icon.png"
apple_touch_icon = "https://www.lunarvim.org/img/lunarvim_icon.png"
android_chrome_512 = "https://www.lunarvim.org/img/lunarvim_icon.png"
android_chrome_192 = "https://www.lunarvim.org/img/lunarvim_icon.png"

[extra.default_author]
name = "silence_zhpf"
avatar = "https://avatars.githubusercontent.com/u/22020318?v=4"
avatar_alt = "silence_zhpf"

